# Generated by Django 4.2.1 on 2023-05-20 10:30

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_name', models.CharField(max_length=150)),
                ('speciality_code', models.CharField(max_length=10)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subject_1', models.CharField(max_length=150)),
                ('subject_2', models.CharField(max_length=150)),
                ('main_image', models.ImageField(blank=True, default='', upload_to='')),
                ('carousel_1', models.ImageField(blank=True, default='', upload_to='')),
                ('carousel_2', models.ImageField(blank=True, default='', upload_to='')),
                ('carousel_3', models.ImageField(blank=True, default='', upload_to='')),
                ('job_outlook', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('salary_range', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_name', models.CharField(default='', max_length=150)),
                ('short_name', models.CharField(default='', max_length=50)),
                ('university_code', models.CharField(default='', max_length=10)),
                ('location', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('number_of_specialties', models.IntegerField(default=0)),
                ('study_language', models.CharField(default='', max_length=100)),
                ('student_count', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('tuition_price', models.IntegerField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, default='', upload_to='')),
                ('main_img', models.ImageField(blank=True, default='', upload_to='')),
                ('student_life', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('dormitory', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('study_abroad_programs', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('clubs_and_organizations', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('athletics', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('alumni', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('accreditation', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('carousel_1', models.ImageField(blank=True, default='', upload_to='')),
                ('carousel_2', models.ImageField(blank=True, default='', upload_to='')),
                ('carousel_3', models.ImageField(blank=True, default='', upload_to='')),
                ('carousel_4', models.ImageField(blank=True, default='', upload_to='')),
                ('carousel_5', models.ImageField(blank=True, default='', upload_to='')),
                ('facebook', models.CharField(default='', max_length=250)),
                ('instagram', models.CharField(default='', max_length=250)),
                ('youtube', models.CharField(default='', max_length=250)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('speciality', models.ManyToManyField(blank=True, to='features.speciality')),
            ],
        ),
        migrations.AddField(
            model_name='speciality',
            name='available_universities',
            field=models.ManyToManyField(related_name='specialities', to='features.university'),
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('education', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('demand', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('employment_outlook', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('salary_range', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, default='', upload_to='')),
                ('carousel_1', models.ImageField(blank=True, default='', upload_to='')),
                ('carousel_2', models.ImageField(blank=True, default='', upload_to='')),
                ('carousel_3', models.ImageField(blank=True, default='', upload_to='')),
                ('specialties', models.ManyToManyField(blank=True, to='features.speciality')),
            ],
        ),
    ]
