# Generated by Django 4.2.1 on 2023-05-20 11:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_speciality_subject_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='skills',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
