# Generated by Django 4.2.1 on 2023-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_profession_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='speciality',
            new_name='specialities',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='available_universities',
        ),
        migrations.AddField(
            model_name='speciality',
            name='universities',
            field=models.ManyToManyField(blank=True, to='features.university'),
        ),
    ]
