# Generated by Django 4.2.1 on 2023-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_rename_speciality_university_specialities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='subject_1',
            field=models.CharField(choices=[('biology', 'Biology'), ('geography', 'Geography'), ('creative exam', 'Creative exam'), ('the World History', 'The World History'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('informatics', 'Informatics'), ('chemistry', 'Chemistry'), ('kazakh language', 'Kazakh language'), ('kazakh literature', 'Kazakh literature'), ('russian language', 'Russian language'), ('russian literature', 'Russian literature'), ('foreign language', 'Foreign language'), ('fundamentals of Law', 'Fundamentals of Law')], max_length=20),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='subject_2',
            field=models.CharField(choices=[('biology', 'Biology'), ('geography', 'Geography'), ('creative exam', 'Creative exam'), ('the World History', 'The World History'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('informatics', 'Informatics'), ('chemistry', 'Chemistry'), ('kazakh language', 'Kazakh language'), ('kazakh literature', 'Kazakh literature'), ('russian language', 'Russian language'), ('russian literature', 'Russian literature'), ('foreign language', 'Foreign language'), ('fundamentals of Law', 'Fundamentals of Law')], max_length=20),
        ),
    ]
