# Generated by Django 4.2.1 on 2023-05-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_alter_speciality_subject_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='alumni',
            new_name='about_university',
        ),
        migrations.RemoveField(
            model_name='university',
            name='athletics',
        ),
        migrations.RemoveField(
            model_name='university',
            name='clubs_and_organizations',
        ),
        migrations.RemoveField(
            model_name='university',
            name='dormitory',
        ),
        migrations.RemoveField(
            model_name='university',
            name='student_life',
        ),
        migrations.RemoveField(
            model_name='university',
            name='study_abroad_programs',
        ),
    ]
