# Generated by Django 4.2.1 on 2023-05-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_rename_alumni_university_about_university_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='carousel_4',
        ),
        migrations.RemoveField(
            model_name='university',
            name='carousel_5',
        ),
    ]
