# Generated by Django 4.2.1 on 2023-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_alter_profession_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='salary_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profession',
            name='salary_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speciality',
            name='salary_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speciality',
            name='salary_to',
            field=models.IntegerField(default=0),
        ),
    ]
