# Generated by Django 4.2.1 on 2023-05-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_profession_salary_from_profession_salary_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='carousel_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profession',
            name='carousel_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profession',
            name='carousel_3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='carousel_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='carousel_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='carousel_3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='university',
            name='carousel_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='university',
            name='carousel_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='university',
            name='carousel_3',
            field=models.CharField(default='', max_length=500),
        ),
    ]
